### PR TITLE
Bump to LoweredCodeUtils 2.4

### LINKED ISSUE #587: MethodError: no method matching add_control_flow!(::BitVector, ::Core.Compiler.CFG, ::BitSet)
This error occurred in our test suite which uses JET. @Drvi notes:

> The crux of the issue is that LoweredCodeUtils changed a  method signature of `add_control_flow!` in this [PR](https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/88) (the last arg of `add_control_flow!` used to be a `BitSet` which is what [JET does](https://github.com/aviatesk/JET.jl/blob/0443cb6aa2c486ff93cb67239028bb16b948a715/src/toplevel/virtualprocess.jl#L1185-L1199)). It seems that `add_control_flow!` is an unexported function, so JET is basically touching internals of this package so semver didn’t guard us here.

```
  MethodError: no method matching add_control_flow!(::BitVector, ::Core.Compiler.CFG, ::BitSet)

  Closest candidates are:
    add_control_flow!(::Any, ::Any, !Matched::AbstractVector{LoweredCodeUtils.Path})
     @ LoweredCodeUtils ~/.julia/packages/LoweredCodeUtils/4GqSU/src/codeedges.jl:762

  Stacktrace:
    [1] select_dependencies!(concretize::BitVector, src::Core.CodeInfo, edges::LoweredCodeUtils.CodeEdges)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:1195
    [2] select_statements(src::Core.CodeInfo)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:1066
    [3] partially_interpret!(interp::JET.ConcreteInterpreter{JET.var"#usemodule_with_err_handling#56"{JET.VirtualProcessResult, String, JET.ToplevelConfig, Int64, Set{Symbol}, Base.RefValue{LineNumberNode}, JET.var"#err_handler#49"{JET.VirtualProcessResult, String, Base.RefValue{LineNumberNode}}}, JET.JETAnalyzer{JET.BasicPass}}, mod::Module, src::Core.CodeInfo)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:1040
    [4] _virtual_process!(res::JET.VirtualProcessResult, toplevelex::Expr, filename::String, analyzer::JET.JETAnalyzer{JET.BasicPass}, config::JET.ToplevelConfig, context::Module, pkg_mod_depth::Int64, force_concretize::Bool)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:804
    [5] _virtual_process!
      @ ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:611 [inlined]
    [6] _virtual_process!(res::JET.VirtualProcessResult, s::String, filename::String, analyzer::JET.JETAnalyzer{JET.BasicPass}, config::JET.ToplevelConfig, context::Module, pkg_mod_depth::Int64)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:591
    [7] virtual_process(x::String, filename::String, analyzer::JET.JETAnalyzer{JET.BasicPass}, config::JET.ToplevelConfig)
      @ JET ~/.julia/packages/JET/wFGWz/src/toplevel/virtualprocess.jl:445
    [8] #analyze_and_report_text!#134
      @ ~/.julia/packages/JET/wFGWz/src/JET.jl:992 [inlined]
    [9] analyze_and_report_file!(analyzer::JET.JETAnalyzer{JET.BasicPass}, filename::String, pkgid::Nothing; jetconfigs::Base.Pairs{Symbol, Any, NTuple{7, Symbol}, NamedTuple{(:ignored_modules, :analyze_from_definitions, :concretization_patterns, :context, :target_defined_modules, :toplevel_logger, :mode), Tuple{Nothing, Bool, Vector{Any}, Module, Bool, Nothing, Symbol}}})
      @ JET ~/.julia/packages/JET/wFGWz/src/JET.jl:800
   [10] analyze_and_report_file! (repeats 2 times)
      @ ~/.julia/packages/JET/wFGWz/src/JET.jl:795 [inlined]
   [11] report_file(args::String; jetconfigs::Base.Pairs{Symbol, Any, NTuple{7, Symbol}, NamedTuple{(:ignored_modules, :analyze_from_definitions, :concretization_patterns, :context, :target_defined_modules, :toplevel_logger, :mode), Tuple{Nothing, Bool, Vector{Any}, Module, Bool, Nothing, Symbol}}})
      @ JET ~/.julia/packages/JET/wFGWz/src/analyzers/jetanalyzer.jl:1665
   [12] report_file
      @ ~/.julia/packages/JET/wFGWz/src/analyzers/jetanalyzer.jl:1662 [inlined]
   [13] jet_test_file(file_path::String; ignored_modules::Nothing, jet_frames_to_skip::Tuple{}, analyze_from_definitions::Bool, concretization_patterns::Vector{Any}, context::Module, target_defined_modules::Bool, mode::Symbol)
      @ Main.var"##JET error analysis from package definitions#318" ~/packages/jet_test_utils.jl:197
...truncated...
```

### PR DESCRIPTION
**Pull request by timholy**
Control-flow analysis changed considerably  in LoweredCodeUtils 2.4
(xref https://github.com/JuliaDebug/LoweredCodeUtils.jl/issues/87).
This updates to the new version. The overall trend is less
reliance on `norequire` as a way of blocking certain "bad"
statements, instead attempting to discover minimal statements
purely by their dependencies.

Fixes #587

### CODE REVIEW

**Comment by timholy** [comment]
Any thoughts on moving `strongly_connected_components` to LoweredCodeUtils? It seems likely to be useful there too.

**Comment by timholy** [comment]
Hmm, those `OutOfMemoryError` errors are not promising. From browsing the history of CI they don't seem typical, so perhaps this change is causing them 😢

**Comment by timholy** [comment]
Likely https://github.com/JuliaDebug/LoweredCodeUtils.jl/issues/96

**Comment by aviatesk** [comment]
Thanks for the update! I had been delaying the LCT update, so this is very helpful.

> The overall trend is less
> reliance on `norequire` as a way of blocking certain "bad"
> statements, instead attempting to discover minimal statements
> purely by their dependencies.

I believe this is a positive trend.

> Any thoughts on moving `strongly_connected_components` to LoweredCodeUtils? It seems likely to be useful there too.

Absolutely! This is code I originally adapted from LightGraphs.jl a while back. While it doesn't have its own unit tests, it has been bug-free in JET's functionality so far. I'll review the most recent code from Graphs.jl and then attempt to create a PR to LCU.

**Comment by timholy** [comment]
Well, at least we don't get out of memory errors. I don't have time to dig into the failures any more today but I am interested in figuring out why things are failing, it could reveal further issues with LCU's current strategy.

**Comment by fingolfin** [comment]
Would be nice to get this to hopefully unbreak JET on Julia master (at least it needs a newer LCU for master, not sure if that's already sufficient)

**Pull request closed without merging**
