### PR TITLE
Add a "stub" version of JET for installation on old Julia

### PR DESCRIPTION
**Pull request by timholy**
This allows packages like SnoopCompile to declare a dependency on JET
while not abandoning older versions of Julia. JET will only be loaded
based on `Base.VERSION`, so this is merely a Pkg-hack.

**DO NOT merge to master!!** I am not sure how one specifies that this should be merged into its own branch. 

EDIT: if you agree that this is fine, I recommend doing the actual release of this v0.0.1 shortly before you release a "real" version of JET. The reason: GitHub advertises the latest release (on the homepage in the "Releases" section)  based on date, not version number, and it might be confusing for users to see that the latest version of this package is 0.0.1. You can wipe that out by doing a real release immediately after the 0.0.1 version gets tagged here.

### CODE REVIEW

**Comment by aviatesk** [comment]
Thanks for bringing this up !
The approach sounds reasonable to me, and let's try it.

I created a branch named `v0.0.1` and it seems like we can merge into it now ?

> EDIT: if you agree that this is fine, I recommend doing the actual release of this v0.0.1 shortly before you release a "real" version of JET.

Thanks for this tip. I'm thinking about releasing v0.5.0 once https://github.com/julia-vscode/julia-vscode/pull/2329 is available, can it happen within few days, @pfitzseb ? Even otherwise I'm also okay with releasing it w/o the VSCode integration, though.

**Comment by pfitzseb** [comment]
Is there any reason to hold up a JET release until that version of the extension is released? Nothing should break when the relevant display methods aren't available, right?

I'm unfortunately not super confident we'll get the next patch out this week...

**Comment by aviatesk** [comment]
> Is there any reason to hold up a JET release until that version of the extension is released? Nothing should break when the relevant display methods aren't available, right?

Yes, I just _hoped_ to release v0.5.0 because the recent refactors are all motivated by the integration :P
I also think the refactors might be worth to have on their own, so I don't think VSCode side integration should block JET v0.5.0.

**Comment by timholy** [comment]
OK, I think this is ready. No rush though, it can wait until it's convenient for you.

**Pull request merged**
