### PR TITLE
Fixing `The applicable method may be too new` in #225

### PR DESCRIPTION
**Pull request by goerch**
... by adding `@invokelatest` to `show_tuple_as_call`

### CODE REVIEW

**Comment by aviatesk** [comment]
`@invokelatest` seems to be too costly to be used in this function (it can be called so often during abstractinterpret).
Can you elaborated why it is needed?

**Comment by goerch** [comment]
> `@invokelatest` seems to be too costly to be used in this function (it can be called so often during abstractinterpret). Can you elaborated why it is needed?

The error I analyzed was 

```
MethodError: no method matching namemap(::Type{Main.##JETVirtualModule#274.OpticSim.AsphericSurfaceType})
The applicable method may be too new: running in world age 31389, while current world is 33912.
```

and the first JET function in the call stack is 

```
@inline function show_tuple_as_call(io::IO, name::Symbol, @nospecialize(sig::Type))
    @static if hasmethod(Base.show_tuple_as_call, (IO, Symbol, Type), (:demangle, :kwargs, :argnames, :qualified))
        Base.show_tuple_as_call(io, name, sig; qualified = true)
    else
        Base.show_tuple_as_call(io, name, sig, false, nothing, nothing, true)
    end
end
```

The Internet taught me, that `@invokelatest` is a possible solution?

**Comment by aviatesk** [comment]
`@invokelatest f(args...)` means "run `f(args...)` with newest definitions of all methods involved with the entire callstack of it". It essentially hinders the compiler to do any sort of optimization on `f(args...)` statically. So we want to apply it to the smallest region as possible. And I'd like to argue that it's always better to understand the root of the problem.

**Comment by aviatesk** [comment]
Well, at least from the benchmark above, it might be okay to give up using it there if it turns out to be too complicated to figure out the problem :p

**Comment by goerch** [comment]
> `@invokelatest f(args...)` means "run `f(args...)` with newest definitions of all methods involved with the entire callstack of it". It essentially hinders the compiler to do any sort of optimization on `f(args...)` statically. So we want to apply it to the smallest region as possible. And I'd like to argue that it's always better to understand the root of the problem.

Here the complete call stack FYI:

```
[toplevel-info] analyzing from top-level definitions ... 934/2060ERROR: MethodError: no method matching namemap(::Type{Main.##JETVirtualModule#274.OpticSim.AsphericSurfaceType})
The applicable method may be too new: running in world age 31389, while current world is 33969.
Closest candidates are:
  namemap(::Type{Main.##JETVirtualModule#274.OpticSim.AsphericSurfaceType}) at C:\Users\Win10\AppData\Local\Programs\Julia-1.7.0\share\julia\base\Enums.jl:201 (method too new to be called from 
this world context.)
  namemap(::Type{Main.##JETVirtualModule#274.OpticSim.InterfaceMode}) at C:\Users\Win10\AppData\Local\Programs\Julia-1.7.0\share\julia\base\Enums.jl:201 (method too new to be called from this world context.)
  namemap(::Type{MbedTLS.CipherMode}) at C:\Users\Win10\AppData\Local\Programs\Julia-1.7.0\share\julia\base\Enums.jl:201 (method too new to be called from this world context.)
  ...
Stacktrace:
  [1] _symbol(x::Main.##JETVirtualModule#274.OpticSim.AsphericSurfaceType)
    @ Base.Enums .\Enums.jl:29
  [2] show(io::IOContext{IOBuffer}, x::Main.##JETVirtualModule#274.OpticSim.AsphericSurfaceType)
    @ Base.Enums .\Enums.jl:37
  [3] show_typeparams(io::IOContext{IOBuffer}, env::Core.SimpleVector, orig::Core.SimpleVector, wheres::Vector{TypeVar})
    @ Base .\show.jl:640
  [4] show_datatype(io::IOContext{IOBuffer}, x::DataType, wheres::Vector{TypeVar})
    @ Base .\show.jl:1011
  [5] _show_type(io::IOContext{IOBuffer}, x::Type)
    @ Base .\show.jl:923
  [6] show(io::IOContext{IOBuffer}, x::Type)
    @ Base .\show.jl:881
  [7] sprint(f::Function, args::Type; context::IOBuffer, sizehint::Int64)
    @ Base .\strings\io.jl:112
  [8] #print_type_stacktrace#485
    @ .\show.jl:2399 [inlined]
  [9] print_type_stacktrace(io::IOBuffer, type::Type)
    @ Base .\show.jl:2399
 [10] show_tuple_as_call(io::IOBuffer, name::Symbol, sig::Type; demangle::Bool, kwargs::Nothing, argnames::Nothing, qualified::Bool, hasfirst::Bool)
    @ Base .\show.jl:2380
 [11] show_tuple_as_call(io::IOBuffer, name::Symbol, sig::Type)
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\inferenceerrorreport.jl:129
 [12] sprint(::Function, ::Symbol, ::Vararg{Any}; context::Nothing, sizehint::Int64)
    @ Base .\strings\io.jl:114
 [13] sprint
    @ .\strings\io.jl:108 [inlined]
 [14] get_sig
    @ C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\inferenceerrorreport.jl:109 [inlined]
 [15] get_virtual_frame(linfo::Core.MethodInstance)
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\inferenceerrorreport.jl:79
 [16] JET.UncaughtExceptionReport(sv::Core.Compiler.InferenceState, throw_calls::Vector{Tuple{Int64, Expr}})
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\analyzers\jetanalyzer.jl:232
 [17] report_uncaught_exceptions!(frame::Core.Compiler.InferenceState, stmts::Vector{Any})
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\analyzers\jetanalyzer.jl:294
 [18] BasicPass
    @ C:\Users\Win10\Documents\GitHub\JET.jl\src\analyzers\jetanalyzer.jl:249 [inlined]
 [19] finish!(analyzer::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, frame::Core.Compiler.InferenceState)
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\analyzers\jetanalyzer.jl:173
 [20] _typeinf(analyzer::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, frame::Core.Compiler.InferenceState)
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\typeinfer.jl:657
 [21] typeinf(interp::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, frame::Core.Compiler.InferenceState)
    @ Core.Compiler .\compiler\typeinfer.jl:209
 [22] typeinf(analyzer::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, frame::Core.Compiler.InferenceState)
    @ JET C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\typeinfer.jl:528
 [23] typeinf_edge(interp::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, method::Method, atypes::Any, sparams::Core.SimpleVector, caller::Core.Compiler.InferenceState)     
    @ Core.Compiler .\compiler\typeinfer.jl:823
 [24] typeinf_edge
    @ C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\typeinfer.jl:347 [inlined]
 [25] abstract_call_method(interp::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, method::Method, sig::Any, sparams::Core.SimpleVector, hardlimit::Bool, sv::Core.Compiler.InferenceState)
    @ Core.Compiler .\compiler\abstractinterpretation.jl:504
 [26] abstract_call_method
    @ C:\Users\Win10\Documents\GitHub\JET.jl\src\abstractinterpret\typeinfer.jl:170 [inlined]
 [27] abstract_call_gf_by_type(interp::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, f::Any, fargs::Vector{Any}, argtypes::Vector{Any}, atype::Any, sv::Core.Compiler.InferenceState, max_methods::Int64)
    @ Core.Compiler .\compiler\abstractinterpretation.jl:105
 [28] abstract_call_gf_by_type
    @ C:\Users\Win10\Documents\GitHub\JET.jl\src\analyzers\jetanalyzer.jl:331 [inlined]
 [29] abstract_call_known(interp::JET.JETAnalyzer{JET.BasicPass{typeof(JET.basic_function_filter)}}, f::Any, fargs::Vector{Any}, argtypes::Vector{Any}, sv::Core.Compiler.InferenceState, max_methods::Int64)
    @ Core.Compiler .\compiler\abstractinterpretation.jl:1342
```

I see two possible angles of attack: either we learn about the change in world age in JET or we include `SnoopCompile` (somehow?) into the analysis.

**Comment by goerch** [comment]
OK, more information. With

```
invalidations = @snoopr (try JET.report_package("OpticSim"); catch e end;)
length(uinvalidated(invalidations))
```

we get

```
10535
```

and 

```
trees = invalidation_trees(invalidations)
```

yields [snoopcompile.txt](https://github.com/aviatesk/JET.jl/files/7656730/snoopcompile.txt)

**Comment by goerch** [comment]
`OpticSim` seems to generate code via [`eval`](https://github.com/microsoft/OpticSim.jl/blob/a3e10a07dcc8f55f2d9c691714db6c3a5e80d889/src/Optical/LensAssembly.jl#L173-L222) and guards against world age problems itself https://github.com/microsoft/OpticSim.jl/blob/a3e10a07dcc8f55f2d9c691714db6c3a5e80d889/src/Optical/LensAssembly.jl#L224-L251. So my current understanding is: we could inherit world age problems from packages under inspection and have two questions

- where do we have to guard against world age problems?
- should we use the same trick as `OpticSim` does?

**Comment by goerch** [comment]
The current critical problem with `channels` is reported in #153. For `subtype` I hit `AssertionError("is_leaf(frame)")` in `step_expr!`. In which of my branches do you want me to try to fix this?

**Comment by aviatesk** [comment]
Fixed by #358 .

**Pull request closed without merging**
